// test-extreme-recursion.script
print("=== 极限递归测试 ===")

// 非尾递归
let sumNormal = (n) => {
    if n <= 0 then {
        0
    } else {
        n + sumNormal(n - 1)
    }
}

let testBoth = (n) => {
    print("n = " + n)
    
    let start = now()
    let result1 = sumNormal(n)
    let mid = now()

    print("递归: " + result1 + " (" + (mid - start)  / 10000 + "ms)")
}

testBoth(100)
testBoth(500)
testBoth(1000)
testBoth(5000)  // 可能栈溢出
testBoth(1000000)  // 可能栈溢出