// test-import.script
import { createStore } from "pinia.script"

let store = createStore({
    state = () => {
        return { x = 0, y = 0 }
    },
    getters = {
        getData = (state) => {
            if(state == null) then {
                return state == null
            }else {
                return  "current value : " + state.x + "," + state.y
            }
            

        }
    },
    actions = {
        increment = (state, n) => {
            state.x = state.x + n
            state.y = state.y - n
        }
    }
})

return { store  }