let createHugeData = () => {
    var hugeArray = []
    
    // 创建大数组
    for i in range(0, 100) {
        print(i)
        hugeArray = hugeArray + {
            id = i,
            name = "item_" + i,
            data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            nested = {
                x = i * 1,
                y = i * 2,
                z = i * 3
            }
        }
    }
    let len = hugeArray.length
    return () => len  // 闭包应该只捕获 len
}

let getLength = createHugeData()
let length = getLength()
print("len : "+length)


